default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: legal_easy_development
  host: backend-postgres-1  # Ensure this is correct for your development environment
  username: postgres
  password: postgres

test:
  <<: *default
  database: legal_easy_test
  host: backend-postgres-1  # Ensure this is correct for your test environment
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: legal_easy_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>  # Ensure this is set properly for production
