default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: legal_easy_development

test:
  <<: *default
  database: legal_easy_test
  username: postgres
  password: password
  host: <%= ENV['DB_HOST'] || 'localhost' %>

production:
  <<: *default
  database: legal_easy_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
