default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: legal_easy_development

test:
  <<: *default
  database: legal_easy_test
  username: <%= ENV['DATABASE_USERNAME'] %>  # Use the correct user for testing
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: postgres  # Make sure this is the same name as the service in GitHub Actions

production:
  <<: *default
  database: legal_easy_production  # Make sure this matches the DB name
  username: <%= ENV['DATABASE_USERNAME'] %>  # Use the env var for consistency
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

