default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development
  username: daniellecardona
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: localhost  

test:
  <<: *default
  database: backend_test
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "" } %>
  host: localhost  

production:
  <<: *default
  database: backend_production
  username: daniellecardona
  password: <%= ENV.fetch("PGPASSWORD") { "" } %>  
  host: localhost  
