name: CI

on:
  push:
    branches:
      - main
      - test_ci
  pull_request:
    branches:
      - main
      - test_ci

jobs:
  backend:
    runs-on: ubuntu-latest

    # services:
      # postgres:
      #   image: postgres:14
      #   ports:
      #     - 5432:5432
      #   env:
      #     POSTGRES_USER: ${{ secrets.PGUSER }}
      #     POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
      #     POSTGRES_DB: backend_test
      #   options: >-
      #     --health-cmd="pg_isready -U postgres"
      #     --health-interval=10s
      #     --health-timeout=5s
      #     --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install backend dependencies
        run: |
          cd backend
          bundle install

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build and run containers
        run: |
          docker-compose -f ../docker-compose.yml up -d

      # - name: Wait for PostgreSQL to be ready
      #   run: |
      #     while ! docker exec backend pg_isready -h postgres -U postgres; do
      #       echo "Waiting for PostgreSQL to be ready..."
      #       sleep 1
      #     done

      # - name: Run database setup
      #   run: |
      #     docker-compose exec backend rake db:create db:migrate

      - name: Run backend tests
        run: |
          docker-compose exec backend bundle exec rspec
