name: CI

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: my_database
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2  

      - name: Install backend dependencies
        run: |
          cd backend
          bundle install

      - name: Set up database
        run: |
          cd backend
          # Wait for PostgreSQL to be ready (use the 'postgres' service name)
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres -p 5432 -U postgres; do
            echo "PostgreSQL not ready, waiting..."
            sleep 5
          done
          echo "PostgreSQL is ready, proceeding with setup..."

          # Run database migrations
          bundle exec rake db:create
          bundle exec rake db:migrate
          # Optionally, you can also seed the database if needed
          # bundle exec rake db:seed

      - name: Show PostgreSQL logs
        run: |
          echo "Showing PostgreSQL container logs for troubleshooting"
          docker logs $(docker ps -q --filter "ancestor=postgres:13")

      - name: Run backend tests
        run: |
          cd backend
          bundle exec rspec

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.6.1'  

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm run test:ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Deploy frontend to production (if on main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST https://api.vercel.com/v13/deployments \
            -H 'Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{
                  "name": "legal-easy",
                  "target": "production",
                  "gitSource": {
                    "branch": "main",
                    "ref": "refs/heads/main"}
                }'

      - name: Deploy frontend to preview (if pull request)
        if: github.event_name == 'pull_request'
        run: |
          curl -X POST https://api.vercel.com/v13/deployments \
            -H 'Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{
                  "name": "legal-easy",
                  "target": "preview",
                  "gitSource": {"branch": "${{ github.head_ref }}"}
                }'
